name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: ccbv
          POSTGRES_USER: classy
          POSTGRES_PASSWORD: classy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.*.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.prod.txt -r requirements.dev.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run Python tests
        env:
          DATABASE_URL: postgres://classy:classy@localhost/ccbv
        run: |
          make test

      - name: Check mypy ratchet for changes
        run: |
          make mypy
